[package]
name = "viceptica"
version = "0.1.0"
edition = "2021"

[dependencies]
glow = "0.16.0"
glutin = "0.31.2"
glutin-winit = "0.4.2"
winit = { version = "0.29.10", features = ["rwh_05"] }
raw-window-handle = "0.5"
cgmath = "0.18.0"
image = "0.25.6"
tobj = "4.0.3"
